version: '3.0'
services:
  rhasspy:
    image: rhasspy
    build: .
    ports:
      - 12101:12101
      - 12183:12183
    volumes:
      - $HOME/.config/rhasspy/profiles:/profiles
      - /run/user/${UID}/pulse:/var/run/pulse
      - $HOME/.config/pulse:/home/pacat/.config/pulse
      - /var/lib/dbus:/var/lib/dbus
      - ${HOME}/.pulse:/home/pacat/.pulse
      - /home/philtweir/Code/rasa-docker:/tmp/rasa-docker
    user: "1001"
    privileged: true
    command: ["--user-profiles", "/profiles", "--profile", "en"]
    devices:
      - /dev/snd:/dev/snd
    links:
      - marytts:marytts
      - home-assistant:home-assistant
    depends_on:
      - marytts
      - home-assistant

  marytts:
    image: sttsse/marytts
    volumes:
      - ./maryhome:/home
    ports:
      - 59125:59125

  home-assistant:
    ports:
      - 8123:8123
    volumes:
      - /home/$USER/.home-assistant:/config
      - /home/$USER/Code/rasa-docker/rhasspy/tts.py:/usr/src/homeassistant/homeassistant/components/marytts/tts.py
      - /home/$USER/Code/rasa-docker/rhasspy/__init__.py:/usr/src/homeassistant/homeassistant/components/tts/__init__.py
    environment:
      - TZ=Europe/London"
    image: homeassistant/home-assistant:stable

  hss-server:
    volumes:
      - ./hss-server/config/skills:/home/user/.config/hss_server/skills
      - ./hss-server/config/config.ini:/home/user/.config/hss_server/config.ini
    image: hss-server
    links:
      - rhasspy:rhasspy
    depends_on:
      - rhasspy
